pipeline:
    name: Go Demo_111_delete
    identifier: Go_Demo_111
    projectIdentifier: Product_Demos_CIE
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Build Test and Push
              identifier: Test_Build_and_Push
              type: CI
              spec:
                  cloneCodebase: true
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: print content 233
                                identifier: print_content
                                spec:
                                    connectorRef: account.nofar_dockerhub
                                    image: alpine
                                    command: echo "main"
                                    privileged: false
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.k8scluster
                          namespace: harness-delegate-pmdemo
              variables:
                  - name: myStageVar
                    type: String
                    value: stageVarValue
    properties:
        ci:
            codebase:
                connectorRef: account.goHelloWorldServer_repo
                build: <+input>
    variables:
        - name: pipelineVar
          type: String
          value: pipelineVarValue
