on:
  push:
    branches:
    
jobs:
  script:
    name: my-script
    runs-on: ubuntu-latest
    steps:
    - name: script
      run: |
        echo "Hello"
        git clone https://github.com/xi3393-hsharma/harness-demo.git
        cd harness-demo
        git config --global user.name xi3393-hsharma
        git config --global user.email hridyanshu.sharma@xebia.com
        git remote add test https://github.com/xi3393-hsharma/test.git
        git push test --all
