on:
  push:
    branches:
    
jobs:
  script:
    name: my-script
    runs-on: ubuntu-latest
    steps:
    - name: script
      run: |
        echo "Hello"
        git clone https://github.com/xi3393-hsharma/harness-demo.git
        cd harness-demo
        git remote add test https://xi3393-hsharma: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@github.com/xi3393-hsharma/test.git
        git push test --all
