on:
  push:
    branches:
    
jobs:
  script:
    name: my-script
    runs-on: ubuntu-latest
    steps:
    - name: script
      run: |
        echo "Hello"
        git clone https://github.com/xi3393-hsharma/harness-demo.git
        cd harness-demo
